give @s zg:oak_stick_block
give @s zg:jungle_stick_block
give @s zg:side_mushroom
give @s zg:dark_stick_block
give @s zg:birch_stick_block
give @s zg:pinecone
give @s zg:seashell
give @s zg:spruce_stick_block
give @s zg:leaf_pile
give @s zg:gravestone
give @s zg:rock_model_l
give @s zg:rock_model_lv
give @s zg:rock_model_lll
give @s zg:mysterious_egg
give @s zg:rock_model_ll
give @s zg:rock_model_v
give @s zg:sandstone_rock_model_l
give @s zg:sandstone_rock_model_lll
give @s zg:sandstone_rock_model_lv
give @s zg:sandstone_rock_model_v
give @s zg:sandstone_rock_model_ll
give @s zg:hostile_bone_model_ll
give @s zg:hostile_bone_model_l
give @s zg:leaf
give @s zg:sandstone_rock_entity
give @s zg:rock_entity
