give @s pa:komos
give @s pa:vish_berrt
give @s pa:mini_cactus
give @s pa:sand_grass
give @s pa:ris_leather
give @s pa:rog_ieti
give @s pa:icestone
give @s pa:chanhchk
give @s pa:soulo
give @s pa:blaze_sword
give @s pa:trillium_plank
give @s pa:ice_axe
give @s pa:rod
give @s pa:palm_pis
give @s pa:icestone_bricks
give @s pa:polished_icestone
give @s pa:kokos_milk
give @s pa:kokos_os
give @s pa:kokos_n
give @s pa:icestone_ieti
give @s pa:sera_ore
give @s pa:deepslate_sera
give @s pa:sera
give @s pa:banana
give @s pa:golden_banana
give @s pa:nautilus_ore
give @s pa:nautilus_meal
give @s pa:cherry
give @s pa:stone_shell
give @s pa:iogurt_bucket
give @s pa:copperstep_disk
give @s pa:swampstep_disk
give @s pa:hrinzatema_stair
give @s pa:trillium_fence
give @s pa:trillium_stair
give @s pa:hrinzatema_slab
give @s pa:hrinzatema_fence
give @s pa:palm_stair
give @s pa:palm_slab
give @s pa:palm_fence
give @s pa:icestone_slab
give @s pa:tfxr7dxr8dtd8x
give @s pa:icestone_stair
give @s pa:itctudd
give @s pa:dtxirditdditdtixdtixtdxdto
give @s pa:fxtfxdxilcd
give @s pa:pilestone
give @s pa:gorill_wall
give @s pa:trillium_slab
give @s pa:polished_pilestone
give @s pa:goat_scull
give @s pa:chitin
give @s pa:waalal
give @s pa:orangutang_wall
give @s pa:spore
give @s pa:ll
give @s pa:shsrf_ghb
give @s pa:forest_pocoh
give @s pa:stone_forrst_shard
give @s pa:sxuna
give @s pa:bi_yetti_hor
give @s pa:top_secret
give @s pa:infected_wood
give @s pa:ender_wood
give @s pa:chitin_shield
give @s pa:hrinzatema_wood
give @s pa:trillium_wood
give @s pa:jclmjchk
give @s pa:ojfnv
give @s pa:palm_log1
give @s pa:banana_block
give @s pa:palm_log2
give @s pa:forest_stone
give @s pa:guardian_totem
give @s pa:dax_totem
give @s pa:stone_shell_naut
