give @s bt:mb.cobblestone
give @s bt:mb.crafting_table
give @s bt:mb.crimson_nylium
give @s bt:mb.crimson_planks
give @s bt:mb.crimson_stem
give @s bt:mb.crying_obsidian
give @s bt:mb.cyan_concrete
give @s bt:mb.dark_oak_log
give @s bt:mb.dark_oak_planks
give @s bt:mb.dark_prismarine
give @s bt:mb.diamond_block
give @s bt:mb.diamond_ore
give @s bt:mb.diorite
give @s bt:mb.dirt
give @s bt:mb.dispenser
give @s bt:mb.dried_kelp_block
give @s bt:mb.dropper
give @s bt:mb.emerald_block
give @s bt:mb.emerald_ore
give @s bt:mb.enchanting_table
give @s bt:mb.ender_chest
give @s bt:mb.end_stone_bricks
give @s bt:mb.end_stone
give @s bt:mb.fire_coral_block
give @s bt:mb.fletching_table
give @s bt:mb.furnace