give @s bt:mb.gilded_blackstone
give @s bt:mb.glowstone
give @s bt:mb.gold_block
give @s bt:mb.gold_ore
give @s bt:mb.granite
give @s bt:mb.grass_block
give @s bt:mb.gravel
give @s bt:mb.gray_concrete
give @s bt:mb.green_concrete
give @s bt:mb.hay_block
give @s bt:mb.honeycomb_block
give @s bt:mb.honey_block
give @s bt:mb.horn_coral_block
give @s bt:mb.iron_block
give @s bt:mb.iron_ore
give @s bt:mb.jukebox
give @s bt:mb.jungle_log
give @s bt:mb.jungle_planks
give @s bt:mb.lapis_block
give @s bt:mb.lapis_ore
give @s bt:mb.light_blue_concrete
give @s bt:mb.light_gray_concrete
give @s bt:mb.lime_concrete
give @s bt:mb.lodestone
give @s bt:mb.loom
give @s bt:mb.magenta_concrete
give @s bt:mb.magma_block