gamerule sendcommandfeedback false
gamerule commandblockoutput false
effect @e[hasitem={item=m:lead_helmet,location=slot.armor.head}] blindness 0 0 true
effect @e[hasitem={item=m:lead_helmet,location=slot.armor.head}] nausea 0 0 true
effect @e[hasitem={item=m:lead_chestplate,location=slot.armor.chest}] wither 0 0 true
effect @e[hasitem={item=m:lead_chestplate,location=slot.armor.chest}] poison 0 0 true
effect @e[hasitem={item=m:lead_chestplate,location=slot.armor.chest}] hunger 0 0 true
effect @e[hasitem={item=m:lead_leggings,location=slot.armor.legs}] mining_fatigue 0 0 true
effect @e[hasitem={item=m:lead_leggings,location=slot.armor.legs}] weakness 0 0 true
effect @e[hasitem={item=m:lead_boots,location=slot.armor.feet}] levitation 0 0 true
effect @e[hasitem={item=m:lead_boots,location=slot.armor.feet}] slowness 0 0 true
execute @e[hasitem={item=m:rose_gold_leggings,location=slot.armor.legs}] ~ ~ ~ execute @s[hasitem={item=m:rose_gold_boots,location=slot.armor.feet}] ~ ~ ~ execute @s[hasitem={item=m:rose_gold_chestplate,location=slot.armor.chest}] ~ ~ ~ execute @s[hasitem={item=m:rose_gold_helmet,location=slot.armor.head}] ~ ~ ~ effect @s regeneration 1 1 true
execute @e[hasitem={item=m:e_rose_gold_leggings,location=slot.armor.legs}] ~ ~ ~ execute @s[hasitem={item=m:e_rose_gold_boots,location=slot.armor.feet}] ~ ~ ~ execute @s[hasitem={item=m:e_rose_gold_chestplate,location=slot.armor.chest}] ~ ~ ~ execute @s[hasitem={item=m:e_rose_gold_helmet,location=slot.armor.head}] ~ ~ ~ effect @s regeneration 1 2 true
execute @e[hasitem={item=m:potassium_boots,location=slot.armor.feet}] ~ ~ ~ execute @s[hasitem={item=m:potassium_leggings,location=slot.armor.legs}] ~ ~ ~ execute @s[hasitem={item=m:potassium_chestplate,location=slot.armor.chest}] ~ ~ ~ execute @s[hasitem={item=m:potassium_helmet,location=slot.armor.head}] ~ ~ ~ execute @e[r=8,type=tnt] ~ ~ ~ effect @p[r=8] resistance 1 20 true
execute @e[hasitem={item=m:potassium_boots,location=slot.armor.feet}] ~ ~ ~ execute @s[hasitem={item=m:potassium_leggings,location=slot.armor.legs}] ~ ~ ~ execute @s[hasitem={item=m:potassium_chestplate,location=slot.armor.chest}] ~ ~ ~ execute @s[hasitem={item=m:potassium_helmet,location=slot.armor.head}] ~ ~ ~ execute @e[r=8,type=creeper] ~ ~ ~ effect @p[r=8] resistance 1 20 true
execute @e[hasitem={item=m:potassium_boots,location=slot.armor.feet}] ~ ~ ~ execute @s[hasitem={item=m:potassium_leggings,location=slot.armor.legs}] ~ ~ ~ execute @s[hasitem={item=m:potassium_chestplate,location=slot.armor.chest}] ~ ~ ~ execute @s[hasitem={item=m:potassium_helmet,location=slot.armor.head}] ~ ~ ~ execute @e[r=8,type=ender_crystal] ~ ~ ~ effect @p[r=8] resistance 1 20 true
execute @e[hasitem={item=m:potassium_boots,location=slot.armor.feet}] ~ ~ ~ execute @s[hasitem={item=m:potassium_leggings,location=slot.armor.legs}] ~ ~ ~ execute @s[hasitem={item=m:potassium_chestplate,location=slot.armor.chest}] ~ ~ ~ execute @s[hasitem={item=m:potassium_helmet,location=slot.armor.head}] ~ ~ ~ execute @e[r=8,type=fireball] ~ ~ ~ effect @p[r=8] resistance 1 20 true
execute @e[hasitem={item=m:potassium_boots,location=slot.armor.feet}] ~ ~ ~ execute @s[hasitem={item=m:potassium_leggings,location=slot.armor.legs}] ~ ~ ~ execute @s[hasitem={item=m:potassium_chestplate,location=slot.armor.chest}] ~ ~ ~ execute @s[hasitem={item=m:potassium_helmet,location=slot.armor.head}] ~ ~ ~ execute @e[r=8,type=m:francium_explode] ~ ~ ~ effect @p[r=18] resistance 1 20 true
execute @e[hasitem={item=m:potassium_boots,location=slot.armor.feet}] ~ ~ ~ execute @s[hasitem={item=m:potassium_leggings,location=slot.armor.legs}] ~ ~ ~ execute @s[hasitem={item=m:potassium_chestplate,location=slot.armor.chest}] ~ ~ ~ execute @s[hasitem={item=m:potassium_helmet,location=slot.armor.head}] ~ ~ ~ execute @e[r=18,type=m:sodium_tnt] ~ ~ ~ effect @p[r=18] resistance 1 20 true
execute @e[hasitem={item=m:potassium_boots,location=slot.armor.feet}] ~ ~ ~ execute @s[hasitem={item=m:potassium_leggings,location=slot.armor.legs}] ~ ~ ~ execute @s[hasitem={item=m:potassium_chestplate,location=slot.armor.chest}] ~ ~ ~ execute @s[hasitem={item=m:potassium_helmet,location=slot.armor.head}] ~ ~ ~ execute @e[r=18,type=m:cesium_tnt] ~ ~ ~ effect @p[r=18] resistance 1 20 true
execute @e[hasitem={item=m:potassium_boots,location=slot.armor.feet}] ~ ~ ~ execute @s[hasitem={item=m:potassium_leggings,location=slot.armor.legs}] ~ ~ ~ execute @s[hasitem={item=m:potassium_chestplate,location=slot.armor.chest}] ~ ~ ~ execute @s[hasitem={item=m:potassium_helmet,location=slot.armor.head}] ~ ~ ~ execute @e[r=18,type=m:lithium_tnt] ~ ~ ~ effect @p[r=18] resistance 1 20 true