execute @e[type=item,name=youmom] ~~~ kill @e[type=item,name="Raw Tin",r=2,c=1]
execute @e[type=item,name=youmom] ~~~ kill @e[type=item,name="Sulfur",r=2,c=1]
execute @e[type=item,name=youmom] ~~~ kill @e[type=item,name="Xp Orb",r=2,c=1]
execute @e[type=item,name=youmom] ~~~ kill @e[type=item,name="Zirconium",r=2,c=1]
execute @e[type=item,name=youmom] ~~~ kill @e[type=item,name="Jade",r=2,c=1]
execute @e[type=item,name=youmom] ~~~ kill @e[type=item,name="Resonite Shard",r=2,c=1]
execute @e[type=item,name=youmom] ~~~ kill @e[type=item,name="Onyx",r=2,c=1]
execute @e[type=item,name=youmom] ~~~ kill @e[type=item,name="Lead Ingot",r=2,c=1]
execute @e[type=item,name=youmom] ~~~ kill @e[type=item,name="Raw Maganese",r=2,c=1]
execute @e[type=item,name=youmom] ~~~ kill @e[type=item,name="Electrum Nugget",r=2,c=1]
execute @e[type=item,name=youmom] ~~~ kill @e[type=item,name="Diamond",r=2,c=1]
execute @e[type=item,name=youmom] ~~~ kill @e[type=item,name="Carbon (37)",r=2,c=1]
execute @e[type=item,name=youmom] ~~~ kill @e[type=item,name="Carbon (38)",r=2,c=1]
execute @e[type=item,name=youmom] ~~~ kill @e[type=item,name="Raw Aluminum",r=2,c=1]
execute @e[type=item,name=youmom] ~~~ kill @e[type=item,name="Raw Lithium",r=2,c=1]
execute @e[type=item,name=youmom] ~~~ kill @e[type=item,name="Raw Francium",r=2,c=1]
execute @e[type=item,name=youmom] ~~~ kill @e[type=item,name="Raw Sodium",r=2,c=1]
execute @e[type=item,name=youmom] ~~~ kill @e[type=item,name="Raw Cesium",r=2,c=1]
execute @e[type=item,name=youmom] ~~~ kill @e[type=item,name="Raw Potassium",r=2,c=1]
execute @e[type=item,name=youmom] ~~~ kill @e[type=item,name="Raw Rubidium",r=2,c=1]
execute @e[type=item,name=youmom] ~~~ kill @e[type=item,name="Zirconium",r=2,c=1]
execute @e[type=item,name=youmom] ~~~ kill @s