setblock ~1 ~ ~1 shulker_box 11
setblock ~ ~ ~1 shulker_box 12
setblock ~-1 ~ ~1 shulker_box 9
setblock ~1 ~ ~ shulker_box 8
setblock ~-1 ~ ~ shulker_box 5
setblock ~1 ~ ~-1 shulker_box 10
setblock ~ ~ ~-1 shulker_box 14
setblock ~-1 ~ ~-1 shulker_box 4
replaceitem block ~1 ~ ~1 slot.container 0 stonebrick:blue_stonebrick_carved_stairs_0 64
replaceitem block ~1 ~ ~1 slot.container 1 stonebrick:blue_stonebrick_carved_stairs_1 64
replaceitem block ~1 ~ ~1 slot.container 2 stonebrick:blue_stonebrick_carved_stairs_2 64
replaceitem block ~1 ~ ~1 slot.container 3 stonebrick:blue_stonebrick_carved_stairs_3 64
replaceitem block ~1 ~ ~1 slot.container 4 stonebrick:blue_stonebrick_carved_stairs_4 64
replaceitem block ~1 ~ ~1 slot.container 5 stonebrick:blue_stonebrick_carved_stairs_5 64
replaceitem block ~1 ~ ~1 slot.container 6 stonebrick:blue_stonebrick_carved_stairs_6 64
replaceitem block ~1 ~ ~1 slot.container 7 stonebrick:blue_stonebrick_carved_stairs_7 64
replaceitem block ~1 ~ ~1 slot.container 8 stonebrick:blue_stonebrick_carved_stairs_8 64
replaceitem block ~1 ~ ~1 slot.container 9 stonebrick:blue_stonebrick_carved_stairs_9 64
replaceitem block ~1 ~ ~1 slot.container 10 stonebrick:blue_stonebrick_carved_stairs_10 64
replaceitem block ~1 ~ ~1 slot.container 11 stonebrick:blue_stonebrick_carved_stairs_11 64
replaceitem block ~1 ~ ~1 slot.container 12 stonebrick:blue_stonebrick_carved_stairs_12 64
replaceitem block ~1 ~ ~1 slot.container 13 stonebrick:blue_stonebrick_carved_stairs_13 64
replaceitem block ~1 ~ ~1 slot.container 14 stonebrick:blue_stonebrick_carved_stairs_14 64
replaceitem block ~ ~ ~1 slot.container 0 stonebrick:brown_stonebrick_carved_stairs_0 64
replaceitem block ~ ~ ~1 slot.container 1 stonebrick:brown_stonebrick_carved_stairs_1 64
replaceitem block ~ ~ ~1 slot.container 2 stonebrick:brown_stonebrick_carved_stairs_2 64
replaceitem block ~ ~ ~1 slot.container 3 stonebrick:brown_stonebrick_carved_stairs_3 64
replaceitem block ~ ~ ~1 slot.container 4 stonebrick:brown_stonebrick_carved_stairs_4 64
replaceitem block ~ ~ ~1 slot.container 5 stonebrick:brown_stonebrick_carved_stairs_5 64
replaceitem block ~ ~ ~1 slot.container 6 stonebrick:brown_stonebrick_carved_stairs_6 64
replaceitem block ~ ~ ~1 slot.container 7 stonebrick:brown_stonebrick_carved_stairs_7 64
replaceitem block ~ ~ ~1 slot.container 8 stonebrick:brown_stonebrick_carved_stairs_8 64
replaceitem block ~ ~ ~1 slot.container 9 stonebrick:brown_stonebrick_carved_stairs_9 64
replaceitem block ~ ~ ~1 slot.container 10 stonebrick:brown_stonebrick_carved_stairs_10 64
replaceitem block ~ ~ ~1 slot.container 11 stonebrick:brown_stonebrick_carved_stairs_11 64
replaceitem block ~ ~ ~1 slot.container 12 stonebrick:brown_stonebrick_carved_stairs_12 64
replaceitem block ~ ~ ~1 slot.container 13 stonebrick:brown_stonebrick_carved_stairs_13 64
replaceitem block ~ ~ ~1 slot.container 14 stonebrick:brown_stonebrick_carved_stairs_14 64
replaceitem block ~-1 ~ ~1 slot.container 0 stonebrick:cyan_stonebrick_carved_stairs_0 64
replaceitem block ~-1 ~ ~1 slot.container 1 stonebrick:cyan_stonebrick_carved_stairs_1 64
replaceitem block ~-1 ~ ~1 slot.container 2 stonebrick:cyan_stonebrick_carved_stairs_2 64
replaceitem block ~-1 ~ ~1 slot.container 3 stonebrick:cyan_stonebrick_carved_stairs_3 64
replaceitem block ~-1 ~ ~1 slot.container 4 stonebrick:cyan_stonebrick_carved_stairs_4 64
replaceitem block ~-1 ~ ~1 slot.container 5 stonebrick:cyan_stonebrick_carved_stairs_5 64
replaceitem block ~-1 ~ ~1 slot.container 6 stonebrick:cyan_stonebrick_carved_stairs_6 64
replaceitem block ~-1 ~ ~1 slot.container 7 stonebrick:cyan_stonebrick_carved_stairs_7 64
replaceitem block ~-1 ~ ~1 slot.container 8 stonebrick:cyan_stonebrick_carved_stairs_8 64
replaceitem block ~-1 ~ ~1 slot.container 9 stonebrick:cyan_stonebrick_carved_stairs_9 64
replaceitem block ~1 ~ ~ slot.container 0 stonebrick:gray_stonebrick_carved_stairs_0 64
replaceitem block ~1 ~ ~ slot.container 1 stonebrick:gray_stonebrick_carved_stairs_1 64
replaceitem block ~1 ~ ~ slot.container 2 stonebrick:gray_stonebrick_carved_stairs_2 64
replaceitem block ~1 ~ ~ slot.container 3 stonebrick:gray_stonebrick_carved_stairs_3 64
replaceitem block ~1 ~ ~ slot.container 4 stonebrick:gray_stonebrick_carved_stairs_4 64
replaceitem block ~1 ~ ~ slot.container 5 stonebrick:gray_stonebrick_carved_stairs_5 64
replaceitem block ~1 ~ ~ slot.container 6 stonebrick:gray_stonebrick_carved_stairs_6 64
replaceitem block ~1 ~ ~ slot.container 7 stonebrick:gray_stonebrick_carved_stairs_7 64
replaceitem block ~1 ~ ~ slot.container 8 stonebrick:gray_stonebrick_carved_stairs_8 64
replaceitem block ~1 ~ ~ slot.container 9 stonebrick:gray_stonebrick_carved_stairs_9 64
replaceitem block ~1 ~ ~ slot.container 10 stonebrick:gray_stonebrick_carved_stairs_10 64
replaceitem block ~1 ~ ~ slot.container 11 stonebrick:gray_stonebrick_carved_stairs_11 64
replaceitem block ~1 ~ ~ slot.container 12 stonebrick:gray_stonebrick_carved_stairs_12 64
replaceitem block ~1 ~ ~ slot.container 13 stonebrick:gray_stonebrick_carved_stairs_13 64
replaceitem block ~1 ~ ~ slot.container 14 stonebrick:gray_stonebrick_carved_stairs_14 64
replaceitem block ~-1 ~ ~ slot.container 0 stonebrick:green_stonebrick_carved_stairs_0 64
replaceitem block ~-1 ~ ~ slot.container 1 stonebrick:green_stonebrick_carved_stairs_1 64
replaceitem block ~-1 ~ ~ slot.container 2 stonebrick:green_stonebrick_carved_stairs_2 64
replaceitem block ~-1 ~ ~ slot.container 3 stonebrick:green_stonebrick_carved_stairs_3 64
replaceitem block ~-1 ~ ~ slot.container 4 stonebrick:green_stonebrick_carved_stairs_4 64
replaceitem block ~-1 ~ ~ slot.container 5 stonebrick:green_stonebrick_carved_stairs_5 64
replaceitem block ~-1 ~ ~ slot.container 6 stonebrick:green_stonebrick_carved_stairs_6 64
replaceitem block ~-1 ~ ~ slot.container 7 stonebrick:green_stonebrick_carved_stairs_7 64
replaceitem block ~-1 ~ ~ slot.container 8 stonebrick:green_stonebrick_carved_stairs_8 64
replaceitem block ~-1 ~ ~ slot.container 9 stonebrick:green_stonebrick_carved_stairs_9 64
replaceitem block ~-1 ~ ~ slot.container 10 stonebrick:green_stonebrick_carved_stairs_10 64
replaceitem block ~-1 ~ ~ slot.container 11 stonebrick:green_stonebrick_carved_stairs_11 64
replaceitem block ~-1 ~ ~ slot.container 12 stonebrick:green_stonebrick_carved_stairs_12 64
replaceitem block ~-1 ~ ~ slot.container 13 stonebrick:green_stonebrick_carved_stairs_13 64
replaceitem block ~-1 ~ ~ slot.container 14 stonebrick:green_stonebrick_carved_stairs_14 64
replaceitem block ~1 ~ ~-1 slot.container 0 stonebrick:purple_stonebrick_carved_stairs_0 64
replaceitem block ~1 ~ ~-1 slot.container 1 stonebrick:purple_stonebrick_carved_stairs_1 64
replaceitem block ~1 ~ ~-1 slot.container 2 stonebrick:purple_stonebrick_carved_stairs_2 64
replaceitem block ~1 ~ ~-1 slot.container 3 stonebrick:purple_stonebrick_carved_stairs_3 64
replaceitem block ~1 ~ ~-1 slot.container 4 stonebrick:purple_stonebrick_carved_stairs_4 64
replaceitem block ~1 ~ ~-1 slot.container 5 stonebrick:purple_stonebrick_carved_stairs_5 64
replaceitem block ~1 ~ ~-1 slot.container 6 stonebrick:purple_stonebrick_carved_stairs_6 64
replaceitem block ~1 ~ ~-1 slot.container 7 stonebrick:purple_stonebrick_carved_stairs_7 64
replaceitem block ~1 ~ ~-1 slot.container 8 stonebrick:purple_stonebrick_carved_stairs_8 64
replaceitem block ~1 ~ ~-1 slot.container 9 stonebrick:purple_stonebrick_carved_stairs_9 64
replaceitem block ~1 ~ ~-1 slot.container 10 stonebrick:purple_stonebrick_carved_stairs_10 64
replaceitem block ~1 ~ ~-1 slot.container 11 stonebrick:purple_stonebrick_carved_stairs_11 64
replaceitem block ~1 ~ ~-1 slot.container 12 stonebrick:purple_stonebrick_carved_stairs_12 64
replaceitem block ~1 ~ ~-1 slot.container 13 stonebrick:purple_stonebrick_carved_stairs_13 64
replaceitem block ~1 ~ ~-1 slot.container 14 stonebrick:purple_stonebrick_carved_stairs_14 64
replaceitem block ~ ~ ~-1 slot.container 0 stonebrick:red_stonebrick_carved_stairs_0 64
replaceitem block ~ ~ ~-1 slot.container 1 stonebrick:red_stonebrick_carved_stairs_1 64
replaceitem block ~ ~ ~-1 slot.container 2 stonebrick:red_stonebrick_carved_stairs_2 64
replaceitem block ~ ~ ~-1 slot.container 3 stonebrick:red_stonebrick_carved_stairs_3 64
replaceitem block ~ ~ ~-1 slot.container 4 stonebrick:red_stonebrick_carved_stairs_4 64
replaceitem block ~ ~ ~-1 slot.container 5 stonebrick:red_stonebrick_carved_stairs_5 64
replaceitem block ~ ~ ~-1 slot.container 6 stonebrick:red_stonebrick_carved_stairs_6 64
replaceitem block ~ ~ ~-1 slot.container 7 stonebrick:red_stonebrick_carved_stairs_7 64
replaceitem block ~ ~ ~-1 slot.container 8 stonebrick:red_stonebrick_carved_stairs_8 64
replaceitem block ~ ~ ~-1 slot.container 9 stonebrick:red_stonebrick_carved_stairs_9 64
replaceitem block ~ ~ ~-1 slot.container 10 stonebrick:red_stonebrick_carved_stairs_10 64
replaceitem block ~ ~ ~-1 slot.container 11 stonebrick:red_stonebrick_carved_stairs_11 64
replaceitem block ~ ~ ~-1 slot.container 12 stonebrick:red_stonebrick_carved_stairs_12 64
replaceitem block ~ ~ ~-1 slot.container 13 stonebrick:red_stonebrick_carved_stairs_13 64
replaceitem block ~ ~ ~-1 slot.container 14 stonebrick:red_stonebrick_carved_stairs_14 64
replaceitem block ~-1 ~ ~-1 slot.container 0 stonebrick:yellow_stonebrick_carved_stairs_0 64
replaceitem block ~-1 ~ ~-1 slot.container 1 stonebrick:yellow_stonebrick_carved_stairs_1 64
replaceitem block ~-1 ~ ~-1 slot.container 2 stonebrick:yellow_stonebrick_carved_stairs_2 64
replaceitem block ~-1 ~ ~-1 slot.container 3 stonebrick:yellow_stonebrick_carved_stairs_3 64
replaceitem block ~-1 ~ ~-1 slot.container 4 stonebrick:yellow_stonebrick_carved_stairs_4 64
replaceitem block ~-1 ~ ~-1 slot.container 5 stonebrick:yellow_stonebrick_carved_stairs_5 64
replaceitem block ~-1 ~ ~-1 slot.container 6 stonebrick:yellow_stonebrick_carved_stairs_6 64
replaceitem block ~-1 ~ ~-1 slot.container 7 stonebrick:yellow_stonebrick_carved_stairs_7 64
replaceitem block ~-1 ~ ~-1 slot.container 8 stonebrick:yellow_stonebrick_carved_stairs_8 64
replaceitem block ~-1 ~ ~-1 slot.container 9 stonebrick:yellow_stonebrick_carved_stairs_9 64
replaceitem block ~-1 ~ ~-1 slot.container 10 stonebrick:yellow_stonebrick_carved_stairs_10 64
replaceitem block ~-1 ~ ~-1 slot.container 11 stonebrick:yellow_stonebrick_carved_stairs_11 64
replaceitem block ~-1 ~ ~-1 slot.container 12 stonebrick:yellow_stonebrick_carved_stairs_12 64
replaceitem block ~-1 ~ ~-1 slot.container 13 stonebrick:yellow_stonebrick_carved_stairs_13 64
replaceitem block ~-1 ~ ~-1 slot.container 14 stonebrick:yellow_stonebrick_carved_stairs_14 64
