give @s viking:iron_viking_leggings
give @s viking:iron_viking_boots
give @s viking:iron_viking_helmet
give @s viking:iron_viking_chestplate
give @s viking:gold_viking_helmet
give @s viking:viking_helmet
give @s viking:viking_boots
give @s viking:gold_viking_chestplate
give @s viking:gold_viking_leggings
give @s viking:viking_chestplate
give @s viking:netherite_viking_boots
give @s viking:netherite_viking_helmet
give @s viking:diamond_viking_helmet
give @s viking:diamond_viking_boots
give @s viking:diamond_viking_leggings
give @s viking:viking_leggings
give @s viking:gold_viking_axe
give @s viking:netherite_viking_axe
give @s viking:viking_axe
give @s viking:diamond_viking_axe
give @s viking:diamond_viking_chestplate
give @s viking:gold_viking_boots
give @s viking:netherite_viking_leggings
give @s viking:netherite_viking_chestplate
give @s viking:iron_viking_axe
give @s viking_iron_shield:shield
give @s viking_netherite_shield:shield
give @s viking_diamond_shield:shield
give @s viking_gold_shield:shield
